swagger: '2.0'
info:
  title: 'Coffee Shop API'
  description: 'This is a Coffee Shop API used by cashiers and baristas'
  version: '1.0.2'
securityDefinitions:
  basicAuth:
    type: basic
security:
  - basicAuth: []
schemes:
  - https
host: 'cafe.yifanai.com'
basePath: '/v1'
paths:
  /:
    get:
      operationId: listLinks
      description: List all links
      parameters: []
      responses:
        '200':
          description: Links retrieved successfully
          schema:
            type: object
            properties:
              list_menu_items:
                $ref: '#/definitions/menu_link'
              place_an_order:
                $ref: '#/definitions/orders_link'
        '400':
          description: Bad request
        '405':
          description: Not allowed HTTP method is used
      tags:
        - Links
      produces:
        - application/json
  /menu:
    get:
      operationId: listMenuItems
      description: List all menu items (Listing types of coffees & additions)
      parameters:
        - description: type
          enum:
            - coffee
            - addition
          in: query
          name: type
          required: false
          type: string
      responses:
        '200':
          description: Menu listed successfully
          schema:
            type: object
            properties:
              place_an_order:
                $ref: '#/definitions/orders_link'
              results:
                type: array
                items:
                  $ref: '#/definitions/MenuItem'
        '400':
          description: Bad request
        '405':
          description: Not allowed HTTP method is used
      tags:
        - Menu
      produces:
        - application/json
  /orders:
    get:
      operationId: listOrders
      description: List all orders
      parameters: []
      responses:
        '200':
          description: Orders listed successfully
          schema:
            type: object
            properties:
              lookup_an_order:
                $ref: '#/definitions/order_link'
              results:
                type: array
                items:
                  $ref: '#/definitions/Order'
        '400':
          description: Bad request
        '405':
          description: Not allowed HTTP method is used
      tags:
        - Orders
      produces:
        - application/json
    post:
      operationId: createOrder
      description: Create (place) an order
      parameters:
        - name: body
          in: body
          schema:
            $ref: '#/definitions/Order'
      responses:
        '201':
          description: Order created successfully
          schema:
            type: object
            properties:
              update_this_order:
                $ref: '#/definitions/order_link'
              update_payment_for_this_order:
                $ref: '#/definitions/order_link'
              cancel_this_order:
                $ref: '#/definitions/order_link'
              item:
                $ref: '#/definitions/Order'
        '400':
          description: Bad request (invalid order data)
        '405':
          description: Not allowed HTTP method is used
      tags:
        - Order
      consumes:
        - application/json
      produces:
        - application/json
  '/orders/{id}':
    get:
      operationId: retrieveOrder
      description: Retrieve (lookup) an order by id
      parameters:
        - name: id
          in: path
          required: true
          description: order ID
          type: string
      responses:
        '200':
          description: Order retrieved successfully
          schema:
            type: object
            properties:
              update_this_order:
                $ref: '#/definitions/order_link'
              item:
                $ref: '#/definitions/Order'
        '400':
          description: Bad request (invalid order id)
        '404':
          description: Order with the provided ID is not found
        '405':
          description: Not allowed HTTP method is used
      tags:
        - Order
      produces:
        - application/json
    put:
      operationId: updateOrder
      description: Update an order by order ID (for amending an order, canceling an order, updating payment information for an order)
      parameters:
        - name: id
          type: string
          in: path
          required: true
          description: order ID
        - name: body
          in: body
          schema:
            $ref: '#/definitions/Order'
      responses:
        '200':
          description: Order updated successfully
          schema:
            type: object
            properties:
              place_a_new_order:
                $ref: '#/definitions/orders_link'
              update_this_order:
                $ref: '#/definitions/order_link'
              update_payment_for_this_order:
                $ref: '#/definitions/order_link'
              cancel_this_order:
                $ref: '#/definitions/order_link'
              lookup_next_order:
                $ref: '#/definitions/orders_link'
              item:
                $ref: '#/definitions/Order'
        '400':
          description: Bad request (invalid order data)
        '404':
          description: Order with the provided ID is not found
        '405':
          description: Not allowed HTTP method is used
      tags:
        - Order
      consumes:
        - application/json
      produces:
        - application/json
    patch:
      operationId: partialUpdateOrder
      description: Partial update an order by order ID (for amending an order, canceling an order, updating payment information for an order)
      parameters:
        - name: id
          type: string
          in: path
          required: true
          description: order ID
        - name: body
          in: body
          schema:
            $ref: '#/definitions/Order'
      responses:
        '200':
          description: Partial order updated successfully
          schema:
            type: object
            properties:
              place_a_new_order:
                $ref: '#/definitions/orders_link'
              update_this_order:
                $ref: '#/definitions/order_link'
              update_payment_for_this_order:
                $ref: '#/definitions/order_link'
              cancel_this_order:
                $ref: '#/definitions/order_link'
              lookup_next_order:
                $ref: '#/definitions/orders_link'
              item:
                $ref: '#/definitions/Order'
        '400':
          description: Bad request (invalid order data)
        '404':
          description: Order with the provided ID is not found
        '405':
          description: Not allowed HTTP method is used
      tags:
        - Order
      consumes:
        - application/json
      produces:
        - application/json
    delete:
      operationId: destroyOrder
      description: Delete an order by order ID
      parameters:
        - name: id
          type: string
          in: path
          required: true
          description: order ID
      responses:
        '204':
          description: Order deleted successfully
          schema:
            type: object
            properties:
              place_a_new_order:
                $ref: '#/definitions/orders_link'
        '400':
          description: Bad request (invalid order ID)
        '404':
          description: Order with the provided ID is not found
        '405':
          description: Not allowed HTTP method is used
      tags:
        - Order
definitions:
  MenuItem:
    type: object
    properties:
      id:
        type: integer
        example: 1
        readOnly: true
        description: Menu item ID
      name:
        type: string
        example: Latte
        description: Menu item name (of a coffee or an addition)
      type:
        enum:
          - coffee
          - addition
        type: string
        example: coffee
        description: Menu item type (either coffee or addition)
      price:
        type: number
        example: '4'
        description: Menu item price
  Order:
    type: object
    properties:
      id:
        type: integer
        example: 1
        readOnly: true
        description: Order ID
      detail:
        type: string
        example: 1 Latte with skimmed milk
        description: Order detail (coffee and additions)
      clientName:
        type: string
        example: John Doe
        description: Order customer name
      price:
        type: number
        example: '5'
        description: Order total price
      status:
        enum:
          - unpaid
          - cancelled
          - paid
          - finished
        type: string
        example: unpaid
        description: Order status (one of unpaid, cancelled, paid or finished)
      paymentDetail:
        type: string
        example: Cash 5 dollar note
        description: Order payment detail (payment method and change)
  menu_link:
    type: string
    format: uri
    x-nullable: true
    example: '/v1/menu'
  orders_link:
    type: string
    format: uri
    x-nullable: true
    example: '/v1/orders'
  order_link:
    type: string
    format: uri
    x-nullable: true
    example: '/v1/orders/1'
x-components: {}
