# Generated by Django 3.0.8 on 2020-10-11 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20201011_1021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='isSuccessful',
        ),
    ]
