# Generated by Django 3.0.8 on 2020-10-11 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_remove_payment_issuccessful'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='isCancelled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payment',
            name='detail',
            field=models.TextField(blank=True, null=True),
        ),
    ]
