# Generated by Django 3.0.8 on 2020-10-11 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20201011_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='isPaid',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
