# Generated by Django 3.0.8 on 2020-10-12 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_auto_20201011_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paymentDetail',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='isPaid',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
