# Generated by Django 3.0.8 on 2020-10-12 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_auto_20201012_0538'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='isCancelled',
        ),
        migrations.RemoveField(
            model_name='order',
            name='isPaid',
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('cancelled', 'Cancelled'), ('paid', 'Paid'), ('finished', 'Finished')], default='unpaid', max_length=9),
        ),
    ]
